from django.urls import path
from .views import (
    storage_list,
    storage_detail,
    storage_field_preferences,
    storage_project_view,
    volume_list,
    volume_project_view,
    host_list,
    host_detail,
    host_project_view,
    storage_insights_auth,
    storage_insights_systems,
    storage_insights_volumes,
    storage_insights_host_connections,
    mkhost_scripts_view,
    host_wwpns_view,
    check_wwpn_conflicts_view,
    port_list,
    port_detail,
    port_project_view
)

urlpatterns = [
    path("", storage_list, name="storage-list"),
    path("<int:pk>/", storage_detail, name="storage-detail"),
    path("<int:pk>/field-preferences/", storage_field_preferences, name="storage-field-preferences"),
    path("project/<int:project_id>/view/storages/", storage_project_view, name="storage-project-view"),
    path("insights/auth/", storage_insights_auth, name="storage-insights-auth"),
    path("insights/storage-systems/", storage_insights_systems, name="storage-insights-systems"),
    path("insights/volumes/", storage_insights_volumes, name="storage-insights-volumes"),
    path("insights/host-connections/", storage_insights_host_connections, name="storage-insights-host-connections"),
    path("volumes/", volume_list, name="volume_list"),
    path("project/<int:project_id>/view/volumes/", volume_project_view, name="volume-project-view"),
    path("hosts/", host_list, name="host_list"),
    path("hosts/<int:pk>/", host_detail, name="host_detail"),
    path("hosts/<int:host_id>/wwpns/", host_wwpns_view, name="host-wwpns"),
    path("project/<int:project_id>/view/hosts/", host_project_view, name="host-project-view"),
    path("check-wwpn-conflicts/", check_wwpn_conflicts_view, name="check-wwpn-conflicts"),
    path("mkhost-scripts/<int:customer_id>/", mkhost_scripts_view, name="mkhost-scripts"),
    path("ports/", port_list, name="port-list"),
    path("ports/<int:pk>/", port_detail, name="port-detail"),
    path("project/<int:project_id>/view/ports/", port_project_view, name="port-project-view"),
]