from django.urls import path
from .views import (
    storage_list,
    storage_detail,
    storage_field_preferences,
    storage_project_view,
    volume_list,
    volume_detail,
    volume_project_view,
    host_list,
    host_detail,
    host_project_view,
    storage_insights_auth,
    storage_insights_systems,
    storage_insights_volumes,
    storage_insights_host_connections,
    mkhost_scripts_view,
    mkhost_scripts_project_view,
    mkhost_scripts_storage_view,
    host_wwpns_view,
    check_wwpn_conflicts_view,
    port_list,
    port_detail,
    port_project_view,
    port_save_view,
    # DS8000 Volume Range Management
    volume_ranges_list,
    volume_range_create,
    volume_range_delete,
    volume_range_update,
    volume_range_dscli,
    volume_dscli_scripts_project_view,
    volume_dscli_scripts_storage_view,
    # Pool Management
    pool_list,
    pool_detail,
    pool_project_view,
    # Host Cluster Management
    host_cluster_list,
    host_cluster_detail,
    host_cluster_project_view,
    # IBM i LPAR Management
    ibmi_lpar_list,
    ibmi_lpar_detail,
    ibmi_lpar_project_view,
    # Volume Mapping Management
    volume_mapping_list,
    volume_mapping_detail,
    volume_mapping_create,
    volume_mapping_preview,
    volume_mapping_project_view,
    # Volume Mapping Scripts
    volume_mapping_scripts_project_view,
    volume_mapping_scripts_storage_view,
    # MkLCU Scripts (DS8000 CKD)
    mklcu_scripts_project_view,
    mklcu_scripts_storage_view,
    # LSS Summary Management
    lss_summary_list,
    lss_summary_detail,
    lss_summary_bulk_update,
    # PPRC Path Management (DS8000 only)
    pprc_path_list,
    pprc_path_detail,
    pprc_path_available_ports,
    pprc_path_customer_storages,
    # PPRC Replication Group Management
    pprc_group_list,
    pprc_group_detail,
    pprc_group_lss_list,
    pprc_group_lss_detail,
    pprc_group_available_lss,
)

urlpatterns = [
    path("", storage_list, name="storage-list"),
    path("<int:pk>/", storage_detail, name="storage-detail"),
    path("<int:pk>/field-preferences/", storage_field_preferences, name="storage-field-preferences"),
    path("project/<int:project_id>/view/storages/", storage_project_view, name="storage-project-view"),
    path("insights/auth/", storage_insights_auth, name="storage-insights-auth"),
    path("insights/storage-systems/", storage_insights_systems, name="storage-insights-systems"),
    path("insights/volumes/", storage_insights_volumes, name="storage-insights-volumes"),
    path("insights/host-connections/", storage_insights_host_connections, name="storage-insights-host-connections"),
    path("volumes/", volume_list, name="volume_list"),
    path("volumes/<int:pk>/", volume_detail, name="volume-detail"),
    path("project/<int:project_id>/view/volumes/", volume_project_view, name="volume-project-view"),
    path("hosts/", host_list, name="host_list"),
    path("hosts/<int:pk>/", host_detail, name="host_detail"),
    path("hosts/<int:host_id>/wwpns/", host_wwpns_view, name="host-wwpns"),
    path("project/<int:project_id>/view/hosts/", host_project_view, name="host-project-view"),
    path("check-wwpn-conflicts/", check_wwpn_conflicts_view, name="check-wwpn-conflicts"),
    path("mkhost-scripts/<int:customer_id>/", mkhost_scripts_view, name="mkhost-scripts"),
    path("mkhost-scripts/project/<int:project_id>/", mkhost_scripts_project_view, name="mkhost-scripts-project"),
    path("mkhost-scripts/project/<int:project_id>/storage/<int:storage_id>/", mkhost_scripts_storage_view, name="mkhost-scripts-storage"),
    path("volume-scripts/project/<int:project_id>/", volume_dscli_scripts_project_view, name="volume-scripts-project"),
    path("volume-scripts/project/<int:project_id>/storage/<int:storage_id>/", volume_dscli_scripts_storage_view, name="volume-scripts-storage"),
    # Volume Mapping Scripts
    path("volume-mapping-scripts/project/<int:project_id>/", volume_mapping_scripts_project_view, name="volume-mapping-scripts-project"),
    path("volume-mapping-scripts/project/<int:project_id>/storage/<int:storage_id>/", volume_mapping_scripts_storage_view, name="volume-mapping-scripts-storage"),
    # MkLCU Scripts (DS8000 CKD only)
    path("mklcu-scripts/project/<int:project_id>/", mklcu_scripts_project_view, name="mklcu-scripts-project"),
    path("mklcu-scripts/project/<int:project_id>/storage/<int:storage_id>/", mklcu_scripts_storage_view, name="mklcu-scripts-storage"),
    path("ports/", port_list, name="port-list"),
    path("ports/<int:pk>/", port_detail, name="port-detail"),
    path("ports/save/", port_save_view, name="port-save"),
    path("project/<int:project_id>/view/ports/", port_project_view, name="port-project-view"),
    # DS8000 Volume Range Management
    path("<int:storage_id>/volume-ranges/", volume_ranges_list, name="volume-ranges-list"),
    path("<int:storage_id>/volume-ranges/create/", volume_range_create, name="volume-range-create"),
    path("<int:storage_id>/volume-ranges/delete/", volume_range_delete, name="volume-range-delete"),
    path("<int:storage_id>/volume-ranges/update/", volume_range_update, name="volume-range-update"),
    path("<int:storage_id>/volume-ranges/dscli/", volume_range_dscli, name="volume-range-dscli"),
    # Pool Management
    path("pools/", pool_list, name="pool-list"),
    path("pools/<int:pk>/", pool_detail, name="pool-detail"),
    path("<int:storage_id>/pools/", pool_list, name="storage-pool-list"),
    path("project/<int:project_id>/view/pools/", pool_project_view, name="pool-project-view"),
    # Host Cluster Management
    path("host-clusters/", host_cluster_list, name="host-cluster-list"),
    path("host-clusters/<int:pk>/", host_cluster_detail, name="host-cluster-detail"),
    path("<int:storage_id>/host-clusters/", host_cluster_list, name="storage-host-cluster-list"),
    path("project/<int:project_id>/view/host-clusters/", host_cluster_project_view, name="host-cluster-project-view"),
    # IBM i LPAR Management
    path("ibmi-lpars/", ibmi_lpar_list, name="ibmi-lpar-list"),
    path("ibmi-lpars/<int:pk>/", ibmi_lpar_detail, name="ibmi-lpar-detail"),
    path("<int:storage_id>/ibmi-lpars/", ibmi_lpar_list, name="storage-ibmi-lpar-list"),
    path("project/<int:project_id>/view/ibmi-lpars/", ibmi_lpar_project_view, name="ibmi-lpar-project-view"),
    # Volume Mapping Management
    path("volume-mappings/", volume_mapping_list, name="volume-mapping-list"),
    path("volume-mappings/<int:pk>/", volume_mapping_detail, name="volume-mapping-detail"),
    path("volume-mappings/create/", volume_mapping_create, name="volume-mapping-create"),
    path("volume-mappings/preview/", volume_mapping_preview, name="volume-mapping-preview"),
    path("project/<int:project_id>/view/volume-mappings/", volume_mapping_project_view, name="volume-mapping-project-view"),
    # LSS Summary Management (DS8000 only)
    path("<int:storage_id>/lss-summary/", lss_summary_list, name="lss-summary-list"),
    path("<int:storage_id>/lss-summary/<int:pk>/", lss_summary_detail, name="lss-summary-detail"),
    path("<int:storage_id>/lss-summary/bulk-update/", lss_summary_bulk_update, name="lss-summary-bulk-update"),
    # PPRC Path Management (DS8000 only)
    path("<int:storage_id>/pprc-paths/", pprc_path_list, name="pprc-path-list"),
    path("pprc-paths/<int:pk>/", pprc_path_detail, name="pprc-path-detail"),
    path("<int:storage_id>/pprc-paths/available-ports/", pprc_path_available_ports, name="pprc-available-ports"),
    path("pprc-paths/ds8000-storages/", pprc_path_customer_storages, name="pprc-customer-storages"),
    # PPRC Replication Group Management (DS8000 only)
    path("<int:storage_id>/pprc-groups/", pprc_group_list, name="pprc-group-list"),
    path("pprc-groups/<int:pk>/", pprc_group_detail, name="pprc-group-detail"),
    path("pprc-groups/<int:group_id>/lss-mappings/", pprc_group_lss_list, name="pprc-group-lss-list"),
    path("pprc-groups/lss-mappings/<int:pk>/", pprc_group_lss_detail, name="pprc-group-lss-detail"),
    path("<int:storage_id>/pprc-groups/available-lss/", pprc_group_available_lss, name="pprc-available-lss"),
]