# Generated by Django 5.1.6 on 2025-10-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuprecord',
            name='django_version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='backuprecord',
            name='postgres_version',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='backuprecord',
            name='python_version',
            field=models.CharField(max_length=50),
        ),
    ]
