# Generated by Django 5.1.6 on 2025-10-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_alter_backuprecord_django_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupconfiguration',
            name='auto_backup_frequency',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], default='daily', help_text='Frequency of automatic backups', max_length=10),
        ),
        migrations.AlterField(
            model_name='backupconfiguration',
            name='auto_backup_hour',
            field=models.IntegerField(default=2, help_text='Hour of day for automatic backup (0-23) - for daily backups or starting hour for hourly'),
        ),
    ]
