version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sanbox_db
      POSTGRES_USER: sanbox_user
      POSTGRES_PASSWORD: sanbox_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: