# Generated by Django 5.1.6 on 2025-02-23 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='customers.customer')),
                ('users', models.ManyToManyField(related_name='project_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('customer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('san_vendor', models.CharField(choices=[('BR', 'Brocade'), ('CI', 'Cisco')], default='BR', max_length=7)),
                ('cisco_alias', models.CharField(choices=[('device-alias', 'device-alias'), ('fcalias', 'fcalias'), ('wwpn', 'wwpn')], default='device-alias', max_length=15)),
                ('cisco_zoning_mode', models.CharField(choices=[('basic', 'basic'), ('enhanced', 'enhanced')], default='enhanced', max_length=15)),
                ('zone_ratio', models.CharField(choices=[('one-to-one', 'one-to-one'), ('one-to-many', 'one-to-many'), ('all-to-all', 'all-to-all')], default='one-to-one', max_length=20)),
                ('zoning_job_name', models.CharField(default='default_job', max_length=40)),
                ('smartzone_prefix', models.CharField(default='', max_length=25)),
                ('alias_max_zones', models.IntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='core.project')),
            ],
        ),
    ]
