# Generated by Django 5.1.6 on 2025-10-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wwpn', models.CharField(max_length=23)),
                ('use', models.CharField(blank=True, choices=[('init', 'Initiator'), ('target', 'Target'), ('both', 'Both')], max_length=6, null=True)),
                ('cisco_alias', models.CharField(blank=True, choices=[('device-alias', 'device-alias'), ('fcalias', 'fcalias'), ('wwpn', 'wwpn')], default='device-alias', max_length=15, null=True)),
                ('create', models.BooleanField(blank=True, default=False, null=True)),
                ('delete', models.BooleanField(blank=True, default=False, null=True)),
                ('include_in_zoning', models.BooleanField(blank=True, default=False, null=True)),
                ('logged_in', models.BooleanField(blank=True, default=False, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('imported', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('zoneset_name', models.CharField(max_length=200)),
                ('san_vendor', models.CharField(choices=[('BR', 'Brocade'), ('CI', 'Cisco')], default='BR', max_length=7)),
                ('vsan', models.IntegerField(blank=True, null=True)),
                ('exists', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=0, help_text='Version number for optimistic locking')),
            ],
        ),
        migrations.CreateModel(
            name='WwpnPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(help_text="First 4 characters of WWPN (e.g., '5001', '2001', 'c050')", max_length=4, unique=True)),
                ('wwpn_type', models.CharField(choices=[('init', 'Initiator'), ('target', 'Target')], help_text='Whether WWPNs with this prefix should be classified as initiators or targets', max_length=6)),
                ('vendor', models.CharField(blank=True, help_text="Optional vendor name for reference (e.g., 'IBM', 'EMC', 'Brocade')", max_length=100, null=True)),
                ('description', models.CharField(blank=True, help_text='Optional description for this prefix', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WWPN Prefix',
                'verbose_name_plural': 'WWPN Prefixes',
                'ordering': ['prefix'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create', models.BooleanField(blank=True, default=False, null=True)),
                ('delete', models.BooleanField(blank=True, default=False, null=True)),
                ('exists', models.BooleanField(blank=True, default=False, null=True)),
                ('zone_type', models.CharField(blank=True, choices=[('smart', 'smart'), ('standard', 'standard')], max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('imported', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
