# Generated by Django 5.1.6 on 2025-04-29 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('customers', '0001_initial'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('zoneset_name', models.CharField(max_length=200)),
                ('san_vendor', models.CharField(choices=[('BR', 'Brocade'), ('CI', 'Cisco')], default='BR', max_length=7)),
                ('vsan', models.IntegerField(blank=True, null=True)),
                ('exists', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_customer', to='customers.customer')),
            ],
            options={
                'unique_together': {('customer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wwpn', models.CharField(max_length=23)),
                ('use', models.CharField(blank=True, choices=[('init', 'Initiator'), ('target', 'Target'), ('both', 'Both')], max_length=6, null=True)),
                ('cisco_alias', models.CharField(blank=True, choices=[('device-alias', 'device-alias'), ('fcalias', 'fcalias'), ('wwpn', 'wwpn')], default='device-alias', max_length=15, null=True)),
                ('create', models.BooleanField(blank=True, default=False, null=True)),
                ('include_in_zoning', models.BooleanField(blank=True, default=False, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('imported', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alias_host', to='storage.host')),
                ('projects', models.ManyToManyField(related_name='alias_projects', to='core.project')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='storage.storage')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san.fabric')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('fabric', 'name'), ('fabric', 'wwpn')},
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create', models.BooleanField(default=False)),
                ('exists', models.BooleanField(default=False)),
                ('zone_type', models.CharField(choices=[('smart', 'smart'), ('standard', 'standard')], max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('imported', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san.fabric')),
                ('members', models.ManyToManyField(to='san.alias')),
                ('projects', models.ManyToManyField(related_name='zone_projects', to='core.project')),
            ],
        ),
    ]
