# Generated by Django 5.1.6 on 2025-03-07 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='projects',
            field=models.ManyToManyField(related_name='alias_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zonegroup',
            name='projects',
            field=models.ManyToManyField(related_name='zone_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
