# Generated by Django 5.1.6 on 2025-05-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='create',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='exists',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='members',
            field=models.ManyToManyField(blank=True, to='san.alias'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_type',
            field=models.CharField(blank=True, choices=[('smart', 'smart'), ('standard', 'standard')], max_length=100, null=True),
        ),
    ]
