# Generated by Django 5.1.6 on 2025-10-13 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('customers', '0001_initial'),
        ('san', '0001_initial'),
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alias_host', to='storage.host'),
        ),
        migrations.AddField(
            model_name='alias',
            name='projects',
            field=models.ManyToManyField(related_name='alias_projects', to='core.project'),
        ),
        migrations.AddField(
            model_name='alias',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='storage.storage'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_customer', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this fabric', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_fabrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alias',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san.fabric'),
        ),
        migrations.AddField(
            model_name='zone',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san.fabric'),
        ),
        migrations.AddField(
            model_name='zone',
            name='members',
            field=models.ManyToManyField(blank=True, to='san.alias'),
        ),
        migrations.AddField(
            model_name='zone',
            name='projects',
            field=models.ManyToManyField(related_name='zone_projects', to='core.project'),
        ),
        migrations.AlterUniqueTogether(
            name='fabric',
            unique_together={('customer', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together={('fabric', 'name'), ('fabric', 'wwpn')},
        ),
    ]
