# Generated by Django 5.1.6 on 2025-08-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='delete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='delete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
