# Generated by Django 5.1.6 on 2025-08-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0002_alias_delete_zone_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='logged_in',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
