# Generated by Django 5.1.6 on 2025-03-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('san', '0002_alias_projects_zonegroup_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='projects',
            field=models.ManyToManyField(related_name='alias_projects', to='core.project'),
        ),
        migrations.AlterField(
            model_name='zonegroup',
            name='projects',
            field=models.ManyToManyField(related_name='zone_projects', to='core.project'),
        ),
    ]
