# Generated by Django 5.1.6 on 2025-10-22 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_is_implementation_company'),
        ('san', '0003_populate_wwpn_prefixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='domain_id',
            field=models.IntegerField(blank=True, help_text='Fabric domain ID', null=True),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('san_vendor', models.CharField(choices=[('BR', 'Brocade'), ('CI', 'Cisco')], default='BR', max_length=7)),
                ('ip_address', models.CharField(blank=True, help_text='IPv4 or IPv6 address', max_length=45, null=True)),
                ('subnet_mask', models.CharField(blank=True, max_length=45, null=True)),
                ('gateway', models.CharField(blank=True, max_length=45, null=True)),
                ('management_url', models.URLField(blank=True, help_text='Web management interface URL', null=True)),
                ('model', models.CharField(blank=True, help_text='Switch model (e.g., MDS 9148S, G620)', max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware_version', models.CharField(blank=True, help_text='Firmware/OS version', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether switch is currently active/in use')),
                ('location', models.CharField(blank=True, help_text='Physical location (datacenter/rack)', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='customers.customer')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='User who last modified this switch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_switches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Switch',
                'verbose_name_plural': 'Switches',
                'ordering': ['customer__name', 'name'],
                'unique_together': {('customer', 'name')},
            },
        ),
        migrations.AddField(
            model_name='fabric',
            name='switch',
            field=models.ForeignKey(blank=True, help_text='Switch this fabric belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrics', to='san.switch'),
        ),
    ]
