# Generated by Django 5.1.6 on 2025-03-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('san', '0003_alter_alias_projects_alter_zonegroup_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonegroup',
            name='projects',
            field=models.ManyToManyField(related_name='zoneg_projects', to='core.project'),
        ),
    ]
