# Generated by Django 5.1.6 on 2025-03-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('san', '0004_alter_zonegroup_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonegroup',
            name='projects',
        ),
        migrations.AddField(
            model_name='zone',
            name='projects',
            field=models.ManyToManyField(related_name='zone_projects', to='core.project'),
        ),
    ]
