# Generated by Django 5.1.6 on 2025-10-04 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0004_add_zone_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='fabric',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this fabric', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_fabrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabric',
            name='version',
            field=models.IntegerField(default=0, help_text='Version number for optimistic locking'),
        ),
    ]
