# Generated by Django 5.1.6 on 2025-10-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0004_fabric_domain_id_switch_fabric_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='wwnn',
            field=models.CharField(blank=True, help_text='World Wide Node Name (WWNN)', max_length=23, null=True),
        ),
    ]
