# Generated by Django 5.1.6 on 2025-10-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0005_switch_wwnn'),
    ]

    operations = [
        # Add index on Alias.use field for faster filtering by use type
        # This speeds up queries that filter aliases by initiator/target/both
        migrations.AddIndex(
            model_name='alias',
            index=models.Index(fields=['use'], name='san_alias_use_idx'),
        ),

        # Add composite index on Alias (fabric, use) for even faster fabric+use filtering
        # This is the most common query pattern when loading zone member dropdowns
        migrations.AddIndex(
            model_name='alias',
            index=models.Index(fields=['fabric', 'use'], name='san_alias_fabric_use_idx'),
        ),

        # Add index on Alias.include_in_zoning for faster filtering of zoneable aliases
        migrations.AddIndex(
            model_name='alias',
            index=models.Index(fields=['include_in_zoning'], name='san_alias_inc_zoning_idx'),
        ),

        # Add composite index on Alias (fabric, include_in_zoning)
        # This speeds up queries that fetch available aliases for a specific fabric
        migrations.AddIndex(
            model_name='alias',
            index=models.Index(fields=['fabric', 'include_in_zoning'], name='san_alias_fab_inc_idx'),
        ),
    ]
