# Generated by Django 5.1.6 on 2025-03-18 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0005_remove_zonegroup_projects_zone_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='users',
        ),
    ]
