# Generated by Django 5.1.6 on 2025-10-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0006_add_zone_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alias',
            name='san_alias_use_idx',
        ),
        migrations.RemoveIndex(
            model_name='alias',
            name='san_alias_fabric_use_idx',
        ),
        migrations.RemoveIndex(
            model_name='alias',
            name='san_alias_inc_zoning_idx',
        ),
        migrations.RemoveIndex(
            model_name='alias',
            name='san_alias_fab_inc_idx',
        ),
    ]
