# Generated by Django 5.1.6 on 2025-03-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0006_remove_fabric_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fabric',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ZoneGroup',
        ),
    ]
