# Generated by Django 5.1.6 on 2025-10-23 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0007_remove_alias_san_alias_use_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='alias',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this alias', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_aliases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alias',
            name='version',
            field=models.IntegerField(default=0, help_text='Version number for optimistic locking'),
        ),
        migrations.AddField(
            model_name='zone',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this zone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_zones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zone',
            name='version',
            field=models.IntegerField(default=0, help_text='Version number for optimistic locking'),
        ),
    ]
