# Generated by Django 5.1.6 on 2025-03-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0007_alias_notes_fabric_notes_zone_notes_delete_zonegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='create',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='alias',
            name='include_in_zoning',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
