# Generated by Django 5.1.6 on 2025-04-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0008_alter_alias_create_alter_alias_include_in_zoning'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='cisco_alias',
            field=models.CharField(choices=[('device-alias', 'device-alias'), ('fcalias', 'fcalias'), ('wwpn', 'wwpn')], default='device-alias', max_length=15),
        ),
    ]
