# Generated by Django 5.1.6 on 2025-04-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0009_alias_cisco_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='cisco_alias',
            field=models.CharField(blank=True, choices=[('device-alias', 'device-alias'), ('fcalias', 'fcalias'), ('wwpn', 'wwpn')], default='device-alias', max_length=15, null=True),
        ),
    ]
