# Generated by Django 5.1.6 on 2025-04-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0010_alter_alias_cisco_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='imported',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='imported',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
