# Generated by Django 5.1.6 on 2025-10-24 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0010_switchfabric_junction_with_domain_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together={('fabric', 'name')},
        ),
        migrations.RemoveField(
            model_name='alias',
            name='wwpn',
        ),
        migrations.CreateModel(
            name='AliasWWPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wwpn', models.CharField(help_text='World Wide Port Name', max_length=23)),
                ('order', models.IntegerField(default=0, help_text='Order of WWPN in the alias (for preserving import order)')),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_wwpns', to='san.alias')),
            ],
            options={
                'verbose_name': 'Alias WWPN',
                'verbose_name_plural': 'Alias WWPNs',
                'ordering': ['alias', 'order'],
                'unique_together': {('alias', 'order'), ('alias', 'wwpn')},
            },
        ),
    ]
