# Generated by Django 5.1.6 on 2025-04-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0011_alias_imported_zone_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
