# Generated by Django 5.1.6 on 2025-10-30 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_status_projectalias_projectfabric_and_more'),
        ('san', '0011_alter_alias_unique_together_remove_alias_wwpn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='committed',
            field=models.BooleanField(default=False, help_text='Changes approved/finalized'),
        ),
        migrations.AddField(
            model_name='alias',
            name='created_by_project',
            field=models.ForeignKey(blank=True, help_text='Project that originally created this entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_aliases', to='core.project'),
        ),
        migrations.AddField(
            model_name='alias',
            name='deployed',
            field=models.BooleanField(default=False, help_text='Actually deployed to infrastructure'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='committed',
            field=models.BooleanField(default=False, help_text='Changes approved/finalized'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='created_by_project',
            field=models.ForeignKey(blank=True, help_text='Project that originally created this entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fabrics', to='core.project'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='deployed',
            field=models.BooleanField(default=False, help_text='Actually deployed to infrastructure'),
        ),
        migrations.AddField(
            model_name='switch',
            name='committed',
            field=models.BooleanField(default=False, help_text='Changes approved/finalized'),
        ),
        migrations.AddField(
            model_name='switch',
            name='created_by_project',
            field=models.ForeignKey(blank=True, help_text='Project that originally created this entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_switches', to='core.project'),
        ),
        migrations.AddField(
            model_name='switch',
            name='deployed',
            field=models.BooleanField(default=False, help_text='Actually deployed to infrastructure'),
        ),
        migrations.AddField(
            model_name='zone',
            name='committed',
            field=models.BooleanField(default=False, help_text='Changes approved/finalized'),
        ),
        migrations.AddField(
            model_name='zone',
            name='created_by_project',
            field=models.ForeignKey(blank=True, help_text='Project that originally created this entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_zones', to='core.project'),
        ),
        migrations.AddField(
            model_name='zone',
            name='deployed',
            field=models.BooleanField(default=False, help_text='Actually deployed to infrastructure'),
        ),
    ]
