# Generated by Django 5.1.6 on 2025-10-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0012_alias_committed_alias_created_by_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alias',
            name='create',
        ),
        migrations.RemoveField(
            model_name='alias',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='alias',
            name='include_in_zoning',
        ),
        migrations.RemoveField(
            model_name='alias',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='create',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='projects',
        ),
    ]
