# Generated by Django 5.1.6 on 2025-04-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0012_alias_updated_zone_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='san_vendor',
            field=models.CharField(choices=[('BR', 'Brocade'), ('CI', 'Cisco')], default='BR', max_length=7),
        ),
    ]
