# Generated by Django 5.1.6 on 2025-04-29 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('storage_type', models.CharField(choices=[('FlashSystem', 'FlashSystem'), ('DS8000', 'DS8000'), ('Switch', 'Switch'), ('Data Domain', 'Data Domain')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_type', models.CharField(blank=True, max_length=4, null=True)),
                ('model', models.CharField(blank=True, max_length=3, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('system_id', models.CharField(blank=True, max_length=16, null=True)),
                ('wwnn', models.CharField(blank=True, max_length=23, null=True)),
                ('firmware_level', models.CharField(blank=True, max_length=60, null=True)),
                ('primary_ip', models.CharField(blank=True, max_length=11, null=True)),
                ('secondary_ip', models.CharField(blank=True, max_length=11, null=True)),
                ('uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='customers.customer')),
            ],
            options={
                'unique_together': {('customer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_project', to='core.project')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owning_storage', to='storage.storage')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
    ]
