# Generated by Django 5.1.6 on 2025-02-23 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('storage_type', models.CharField(choices=[('FlashSystem', 'FlashSystem'), ('DS8000', 'DS8000'), ('Switch', 'Switch'), ('Data Domain', 'Data Domain')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_type', models.CharField(blank=True, max_length=4, null=True)),
                ('model', models.CharField(blank=True, max_length=3, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('system_id', models.CharField(blank=True, max_length=16, null=True)),
                ('wwnn', models.CharField(blank=True, max_length=23, null=True)),
                ('firmware_level', models.CharField(blank=True, max_length=16, null=True)),
                ('primary_ip', models.CharField(blank=True, max_length=11, null=True)),
                ('secondary_ip', models.CharField(blank=True, max_length=11, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='core.project')),
                ('users', models.ManyToManyField(related_name='storage_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_project', to='core.project')),
                ('users', models.ManyToManyField(related_name='host_users', to=settings.AUTH_USER_MODEL)),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owning_storage', to='storage.storage')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
    ]
