# Generated by Django 5.1.6 on 2025-05-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='primary_ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
