# Generated by Django 5.1.6 on 2025-03-04 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='users',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='users',
        ),
    ]
