# Generated by Django 5.1.6 on 2025-08-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='create',
            field=models.BooleanField(default=False),
        ),
    ]
