# Generated by Django 5.1.6 on 2025-10-17 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('san', '0002_initial'),
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('fc', 'Fibre Channel'), ('ethernet', 'Ethernet')], max_length=10)),
                ('speed_gbps', models.IntegerField(help_text='Port speed in Gbps')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('frame', models.IntegerField(blank=True, null=True)),
                ('io_enclosure', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, choices=[('FICON', 'FICON'), ('SCSI FCP', 'SCSI FCP'), ('NVMe FCP', 'NVMe FCP'), ('TCP/IP', 'TCP/IP'), ('iSCSI', 'iSCSI'), ('RDMA', 'RDMA')], max_length=20, null=True)),
                ('use', models.CharField(blank=True, choices=[('host', 'Host'), ('replication', 'Replication')], max_length=20, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=0, help_text='Version number for optimistic locking')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('alias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ports', to='san.alias')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ports', to='san.fabric')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='User who last modified this port', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_ports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='core.project')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='storage.storage')),
            ],
            options={
                'ordering': ['storage', 'name'],
                'unique_together': {('storage', 'name')},
            },
        ),
    ]
