# Generated by Django 5.1.6 on 2025-09-15 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san', '0004_add_zone_indexes'),
        ('storage', '0002_host_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostWwpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wwpn', models.CharField(help_text='Formatted WWPN (e.g., 50:01:23:45:67:89:AB:CD)', max_length=23)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('alias', 'From Alias')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_wwpns', to='storage.host')),
                ('source_alias', models.ForeignKey(blank=True, help_text="If source_type='alias', this references the source alias", null=True, on_delete=django.db.models.deletion.CASCADE, to='san.alias')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('host', 'wwpn')},
            },
        ),
    ]
