# Generated by Django 5.1.6 on 2025-05-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_storage_primary_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='storage_type',
            field=models.CharField(choices=[('FlashSystem', 'FlashSystem'), ('DS8000', 'DS8000'), ('Switch', 'Switch'), ('Data Domain', 'Data Domain'), ('Unknown', 'Unknown')], max_length=20),
        ),
    ]
