# Generated by Django 5.1.6 on 2025-10-17 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('storage', '0002_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='core.project'),
        ),
    ]
