# Generated by Django 5.1.6 on 2025-10-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_port_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='port',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='port',
            name='wwpn',
            field=models.CharField(blank=True, help_text='World Wide Port Name (with or without colons)', max_length=23, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='speed_gbps',
            field=models.IntegerField(blank=True, help_text='Port speed in Gbps (optional)', null=True),
        ),
    ]
