# Generated by Django 5.1.6 on 2025-10-23 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_port_unique_together_port_wwpn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this host', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_hosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='host',
            name='version',
            field=models.IntegerField(default=0, help_text='Version number for optimistic locking'),
        ),
        migrations.AddField(
            model_name='volume',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this volume', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_volumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volume',
            name='version',
            field=models.IntegerField(default=0, help_text='Version number for optimistic locking'),
        ),
    ]
