# Generated by Django 5.1.6 on 2025-05-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_storage_acknowledged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='data_reduction_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='data_reduction_savings_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='data_reduction_savings_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='host_connections_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='total_compression_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
