# Generated by Django 5.1.6 on 2025-10-25 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_host_last_modified_at_host_last_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('storage', 'name')},
        ),
        migrations.AlterField(
            model_name='host',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owning_storage', to='storage.storage'),
        ),
        migrations.RemoveField(
            model_name='host',
            name='project',
        ),
    ]
