# Generated by Django 5.1.6 on 2025-10-30 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_status_projectalias_projectfabric_and_more'),
        ('storage', '0006_alter_host_unique_together_alter_host_storage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='committed',
            field=models.BooleanField(default=False, help_text='Changes approved/finalized'),
        ),
        migrations.AddField(
            model_name='host',
            name='created_by_project',
            field=models.ForeignKey(blank=True, help_text='Project that originally created this entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hosts', to='core.project'),
        ),
        migrations.AddField(
            model_name='host',
            name='deployed',
            field=models.BooleanField(default=False, help_text='Actually deployed to infrastructure'),
        ),
        migrations.AddField(
            model_name='port',
            name='committed',
            field=models.BooleanField(default=False, help_text='Changes approved/finalized'),
        ),
        migrations.AddField(
            model_name='port',
            name='created_by_project',
            field=models.ForeignKey(blank=True, help_text='Project that originally created this entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ports', to='core.project'),
        ),
        migrations.AddField(
            model_name='port',
            name='deployed',
            field=models.BooleanField(default=False, help_text='Actually deployed to infrastructure'),
        ),
        migrations.AddField(
            model_name='storage',
            name='committed',
            field=models.BooleanField(default=False, help_text='Changes approved/finalized'),
        ),
        migrations.AddField(
            model_name='storage',
            name='created_by_project',
            field=models.ForeignKey(blank=True, help_text='Project that originally created this entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_storage_systems', to='core.project'),
        ),
        migrations.AddField(
            model_name='storage',
            name='deployed',
            field=models.BooleanField(default=False, help_text='Actually deployed to infrastructure'),
        ),
        migrations.AddField(
            model_name='volume',
            name='committed',
            field=models.BooleanField(default=False, help_text='Changes approved/finalized'),
        ),
        migrations.AddField(
            model_name='volume',
            name='created_by_project',
            field=models.ForeignKey(blank=True, help_text='Project that originally created this entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_volumes', to='core.project'),
        ),
        migrations.AddField(
            model_name='volume',
            name='deployed',
            field=models.BooleanField(default=False, help_text='Actually deployed to infrastructure'),
        ),
    ]
