# Generated by Django 5.1.6 on 2025-10-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_host_committed_host_created_by_project_host_deployed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='create',
        ),
        migrations.RemoveField(
            model_name='port',
            name='project',
        ),
    ]
