# Generated by Django 5.1.6 on 2025-05-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_host_cluster_id_alias_host_compression_savings_bytes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='cluster_id_alias',
        ),
        migrations.RemoveField(
            model_name='host',
            name='compression_savings_bytes',
        ),
        migrations.RemoveField(
            model_name='host',
            name='compression_savings_percent',
        ),
        migrations.RemoveField(
            model_name='host',
            name='data_reduction_ratio',
        ),
        migrations.RemoveField(
            model_name='host',
            name='data_reduction_savings_bytes',
        ),
        migrations.RemoveField(
            model_name='host',
            name='data_reduction_savings_percent',
        ),
        migrations.RemoveField(
            model_name='host',
            name='drive_compression_ratio',
        ),
        migrations.RemoveField(
            model_name='host',
            name='drive_compression_savings_bytes',
        ),
        migrations.RemoveField(
            model_name='host',
            name='drive_compression_savings_percent',
        ),
        migrations.RemoveField(
            model_name='host',
            name='host_connections_count',
        ),
        migrations.RemoveField(
            model_name='host',
            name='ip_ports_count',
        ),
        migrations.RemoveField(
            model_name='host',
            name='managed_disks_count',
        ),
        migrations.RemoveField(
            model_name='host',
            name='overprovisioned_capacity_bytes',
        ),
        migrations.RemoveField(
            model_name='host',
            name='pool_compression_ratio',
        ),
        migrations.RemoveField(
            model_name='host',
            name='pool_compression_savings_bytes',
        ),
        migrations.RemoveField(
            model_name='host',
            name='pool_compression_savings_percent',
        ),
        migrations.RemoveField(
            model_name='host',
            name='remaining_unallocated_capacity_bytes',
        ),
        migrations.RemoveField(
            model_name='host',
            name='snapshot_provisioned_capacity_bytes',
        ),
        migrations.RemoveField(
            model_name='host',
            name='snapshot_written_capacity_bytes',
        ),
        migrations.RemoveField(
            model_name='host',
            name='topology',
        ),
        migrations.RemoveField(
            model_name='host',
            name='total_compression_ratio',
        ),
        migrations.RemoveField(
            model_name='host',
            name='total_savings_ratio',
        ),
        migrations.RemoveField(
            model_name='host',
            name='unallocated_volume_capacity_bytes',
        ),
        migrations.RemoveField(
            model_name='host',
            name='volume_groups_count',
        ),
    ]
