# Generated by Django 5.1.6 on 2025-12-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_remove_host_create_remove_port_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='create',
            field=models.BooleanField(default=False, help_text='Include this host in mkhost script generation'),
        ),
    ]
