# Generated by Django 5.1.6 on 2025-05-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_remove_host_cluster_id_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='cluster_id_alias',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='compression_savings_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='compression_savings_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='data_reduction_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='data_reduction_savings_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='data_reduction_savings_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='drive_compression_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='drive_compression_savings_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='drive_compression_savings_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='host_connections_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='ip_ports_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='managed_disks_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='overprovisioned_capacity_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='pool_compression_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='pool_compression_savings_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='pool_compression_savings_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='remaining_unallocated_capacity_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='snapshot_provisioned_capacity_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='snapshot_written_capacity_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='topology',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='total_compression_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='total_savings_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='unallocated_volume_capacity_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='volume_groups_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
