# Generated by Django 5.1.6 on 2025-05-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_storage_cluster_id_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
