# Generated by Django 5.1.6 on 2025-12-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_add_create_field_to_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='create',
        ),
    ]
