# Generated by Django 5.1.6 on 2025-12-18 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_pool_model'),
        ('storage', '0010_remove_create_field_from_host'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='pool_id',
            field=models.CharField(blank=True, help_text='Legacy pool ID string from imports', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pool name (max 16 chars for DS8000 compatibility)', max_length=16)),
                ('storage_type', models.CharField(choices=[('FB', 'Fixed Block'), ('CKD', 'Count Key Data')], default='FB', help_text='FB (Fixed Block) or CKD (Count Key Data) - FlashSystem is always FB', max_length=3)),
                ('committed', models.BooleanField(default=False, help_text='Changes approved/finalized')),
                ('deployed', models.BooleanField(default=False, help_text='Actually deployed to infrastructure')),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=0, help_text='Version number for optimistic locking')),
                ('unique_id', models.CharField(max_length=64, unique=True)),
                ('imported', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created_by_project', models.ForeignKey(blank=True, help_text='Project that originally created this entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pools', to='core.project')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='User who last modified this pool', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_pools', to=settings.AUTH_USER_MODEL)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='storage.storage')),
            ],
            options={
                'ordering': ['storage', 'name'],
                'unique_together': {('storage', 'name')},
            },
        ),
        migrations.AddField(
            model_name='volume',
            name='pool_ref',
            field=models.ForeignKey(blank=True, help_text='Pool this volume belongs to (FK to Pool model)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volumes', to='storage.pool'),
        ),
    ]
