# Generated by Django 5.1.6 on 2025-05-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_storage_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='primary_ip',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='secondary_ip',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
