# Generated by Django 5.1.6 on 2025-12-19 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_add_pool_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='pool_id',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='pool_name',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='pool_ref',
        ),
        migrations.AddField(
            model_name='volume',
            name='pool',
            field=models.ForeignKey(blank=True, help_text='Pool this volume belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volumes', to='storage.pool'),
        ),
    ]
