# Generated by Django 5.1.6 on 2025-05-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_alter_storage_primary_ip_alter_storage_secondary_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('volume_id', models.CharField(max_length=16)),
                ('volume_number', models.IntegerField(blank=True, null=True)),
                ('volser', models.CharField(blank=True, max_length=20, null=True)),
                ('format', models.CharField(blank=True, max_length=10, null=True)),
                ('natural_key', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity_bytes', models.BigIntegerField(blank=True, null=True)),
                ('used_capacity_bytes', models.BigIntegerField(blank=True, null=True)),
                ('used_capacity_percent', models.FloatField(blank=True, null=True)),
                ('available_capacity_bytes', models.BigIntegerField(blank=True, null=True)),
                ('written_capacity_bytes', models.BigIntegerField(blank=True, null=True)),
                ('written_capacity_percent', models.FloatField(blank=True, null=True)),
                ('reserved_volume_capacity_bytes', models.BigIntegerField(blank=True, null=True)),
                ('tier0_flash_capacity_percent', models.FloatField(blank=True, null=True)),
                ('tier1_flash_capacity_percent', models.FloatField(blank=True, null=True)),
                ('scm_capacity_percent', models.FloatField(blank=True, null=True)),
                ('enterprise_hdd_capacity_percent', models.FloatField(blank=True, null=True)),
                ('nearline_hdd_capacity_percent', models.FloatField(blank=True, null=True)),
                ('tier_distribution_percent', models.FloatField(blank=True, null=True)),
                ('tier0_flash_capacity_bytes', models.BigIntegerField(blank=True, null=True)),
                ('tier1_flash_capacity_bytes', models.BigIntegerField(blank=True, null=True)),
                ('scm_capacity_bytes', models.BigIntegerField(blank=True, null=True)),
                ('enterprise_hdd_capacity_bytes', models.BigIntegerField(blank=True, null=True)),
                ('nearline_hdd_capacity_bytes', models.BigIntegerField(blank=True, null=True)),
                ('safeguarded_virtual_capacity_bytes', models.BigIntegerField(blank=True, null=True)),
                ('safeguarded_used_capacity_percentage', models.FloatField(blank=True, null=True)),
                ('safeguarded_allocation_capacity_bytes', models.BigIntegerField(blank=True, null=True)),
                ('shortfall_percent', models.FloatField(blank=True, null=True)),
                ('warning_level_percent', models.FloatField(blank=True, null=True)),
                ('compression_saving_percent', models.FloatField(blank=True, null=True)),
                ('grain_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('compressed', models.BooleanField(blank=True, null=True)),
                ('thin_provisioned', models.CharField(blank=True, max_length=32, null=True)),
                ('encryption', models.CharField(blank=True, max_length=10, null=True)),
                ('flashcopy', models.CharField(blank=True, max_length=10, null=True)),
                ('auto_expand', models.BooleanField(blank=True, null=True)),
                ('easy_tier', models.CharField(blank=True, max_length=32, null=True)),
                ('easy_tier_status', models.CharField(blank=True, max_length=32, null=True)),
                ('pool_name', models.CharField(blank=True, max_length=64, null=True)),
                ('pool_id', models.CharField(blank=True, max_length=64, null=True)),
                ('lss_lcu', models.CharField(blank=True, max_length=10, null=True)),
                ('node', models.CharField(blank=True, max_length=32, null=True)),
                ('block_size', models.IntegerField(blank=True, null=True)),
                ('unique_id', models.CharField(max_length=64, unique=True)),
                ('acknowledged', models.BooleanField(blank=True, null=True)),
                ('status_label', models.CharField(blank=True, max_length=32, null=True)),
                ('raid_level', models.CharField(blank=True, max_length=32, null=True)),
                ('copy_id', models.IntegerField(blank=True, null=True)),
                ('safeguarded', models.CharField(blank=True, max_length=16, null=True)),
                ('last_data_collection', models.BigIntegerField(blank=True, null=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='storage.storage')),
            ],
        ),
    ]
