# Generated by Django 5.1.6 on 2025-05-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='deduplicated',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='fast_write_state',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='formatted',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='io_group',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='scm_available_capacity_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='vdisk_mirror_copies',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='vdisk_mirror_role',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='virtual_disk_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
