# Generated by Django 5.1.6 on 2025-12-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_rename_pool_ref_to_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='unique_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
