# Generated by Django 5.1.6 on 2025-12-31 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_projectibmilpar_projectvolumemapping_and_more'),
        ('storage', '0013_volume_unique_id_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('committed', models.BooleanField(default=False, help_text='Changes approved/finalized')),
                ('deployed', models.BooleanField(default=False, help_text='Actually deployed to infrastructure')),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=0, help_text='Version number for optimistic locking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_project', models.ForeignKey(blank=True, help_text='Project that originally created this entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_host_clusters', to='core.project')),
                ('hosts', models.ManyToManyField(blank=True, help_text='Hosts in this cluster that share volumes', related_name='clusters', to='storage.host')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='User who last modified this host cluster', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_host_clusters', to=settings.AUTH_USER_MODEL)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_clusters', to='storage.storage')),
            ],
            options={
                'ordering': ['storage', 'name'],
                'unique_together': {('storage', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IBMiLPAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('committed', models.BooleanField(default=False, help_text='Changes approved/finalized')),
                ('deployed', models.BooleanField(default=False, help_text='Actually deployed to infrastructure')),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=0, help_text='Version number for optimistic locking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_project', models.ForeignKey(blank=True, help_text='Project that originally created this entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ibmi_lpars', to='core.project')),
                ('hosts', models.ManyToManyField(blank=True, help_text='Hosts in this LPAR that receive distributed volumes', related_name='ibmi_lpars', to='storage.host')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='User who last modified this LPAR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_ibmi_lpars', to=settings.AUTH_USER_MODEL)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ibmi_lpars', to='storage.storage')),
            ],
            options={
                'verbose_name': 'IBM i LPAR',
                'verbose_name_plural': 'IBM i LPARs',
                'ordering': ['storage', 'name'],
                'unique_together': {('storage', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VolumeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('host', 'Host'), ('cluster', 'Host Cluster'), ('lpar', 'IBM i LPAR')], max_length=10)),
                ('lun_id', models.IntegerField(blank=True, null=True)),
                ('committed', models.BooleanField(default=False, help_text='Changes approved/finalized')),
                ('deployed', models.BooleanField(default=False, help_text='Actually deployed to infrastructure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_host', models.ForeignKey(blank=True, help_text='For LPAR targets: the specific host this volume was assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_volume_mappings', to='storage.host')),
                ('created_by_project', models.ForeignKey(blank=True, help_text='Project that originally created this entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_volume_mappings', to='core.project')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='User who last modified this mapping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_volume_mappings', to=settings.AUTH_USER_MODEL)),
                ('target_cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volume_mappings', to='storage.hostcluster')),
                ('target_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_volume_mappings', to='storage.host')),
                ('target_lpar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volume_mappings', to='storage.ibmilpar')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_mappings', to='storage.volume')),
            ],
            options={
                'ordering': ['volume', 'target_type'],
                'indexes': [models.Index(fields=['volume', 'target_type'], name='storage_vol_volume__35fe8c_idx'), models.Index(fields=['target_host'], name='storage_vol_target__26e982_idx'), models.Index(fields=['target_cluster'], name='storage_vol_target__4632ac_idx'), models.Index(fields=['target_lpar'], name='storage_vol_target__846c19_idx')],
            },
        ),
    ]
