# Generated by Django 5.1.6 on 2025-05-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_volume_deduplicated_volume_fast_write_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='acknowledged',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='associated_resource',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='fc_ports_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='host_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='last_data_collection',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='natural_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='storage_system',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='vols_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='volume_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='volumes',
            field=models.ManyToManyField(blank=True, related_name='hosts', to='storage.volume'),
        ),
        migrations.AddField(
            model_name='host',
            name='wwpns',
            field=models.TextField(blank=True, null=True),
        ),
    ]
