# Generated by Django 5.1.6 on 2026-01-01 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_projecthostcluster_host_cluster_and_more'),
        ('storage', '0014_hostcluster_ibmilpar_volumemapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='alias',
            field=models.BooleanField(default=False, help_text='True if this volume is an alias volume'),
        ),
        migrations.CreateModel(
            name='LSSSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lss', models.CharField(help_text='2 hex digit LSS identifier (00-FF)', max_length=2)),
                ('ssid', models.CharField(blank=True, help_text='4 hex digit SSID (e.g., 0000-FFFF)', max_length=4, null=True)),
                ('committed', models.BooleanField(default=False, help_text='Changes approved/finalized')),
                ('deployed', models.BooleanField(default=False, help_text='Actually deployed to infrastructure')),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=1, help_text='Version number for optimistic locking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_project', models.ForeignKey(blank=True, help_text='Project that originally created this entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lss_summaries', to='core.project')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='User who last modified this LSS summary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_lss_summaries', to=settings.AUTH_USER_MODEL)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lss_summaries', to='storage.storage')),
            ],
            options={
                'verbose_name': 'LSS Summary',
                'verbose_name_plural': 'LSS Summaries',
                'ordering': ['storage', 'lss'],
                'unique_together': {('storage', 'lss')},
            },
        ),
    ]
