# Generated by Django 5.1.6 on 2025-05-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_host_acknowledged_host_associated_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='imported',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='imported',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='imported',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
