# Generated by Django 5.1.6 on 2026-01-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_volume_alias_lsssummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='port_id',
            field=models.CharField(blank=True, default='', help_text='Port identifier string', max_length=100),
        ),
        migrations.AlterField(
            model_name='port',
            name='use',
            field=models.CharField(blank=True, choices=[('host', 'Host'), ('replication', 'Replication'), ('both', 'Both')], max_length=20, null=True),
        ),
    ]
