# Generated by Django 5.1.6 on 2026-01-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_add_port_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='capacity_cylinders',
            field=models.IntegerField(blank=True, help_text='Capacity in cylinders for CKD volumes.', null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='ckd_capacity_type',
            field=models.CharField(blank=True, choices=[('bytes', 'Bytes/GiB'), ('cyl', 'Cylinders'), ('mod1', 'Mod1 units (1113 cylinders each)')], default='bytes', help_text='How capacity is specified for CKD volumes.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='ckd_datatype',
            field=models.CharField(blank=True, choices=[('', 'Auto (3390 or 3390-A)'), ('3380', '3380 - Max 3339 cylinders'), ('3390', '3390 - Max 65520 cylinders'), ('3390-A', '3390-A - Extended (>65520 cylinders)')], help_text='CKD datatype. Auto selects 3390 for <=65520 cyl, 3390-A for larger.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='os400_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('A01', 'A01 - Protected 8.59 GiB'), ('A02', 'A02 - Protected 17.18 GiB'), ('A04', 'A04 - Protected 35.39 GiB'), ('A05', 'A05 - Protected 70.55 GiB'), ('A06', 'A06 - Protected 141.12 GiB'), ('A07', 'A07 - Protected 282.35 GiB'), ('099', '099 - Protected Variable'), ('A81', 'A81 - Unprotected 8.59 GiB'), ('A82', 'A82 - Unprotected 17.18 GiB'), ('A84', 'A84 - Unprotected 35.39 GiB'), ('A85', 'A85 - Unprotected 70.55 GiB'), ('A86', 'A86 - Unprotected 141.12 GiB'), ('A87', 'A87 - Unprotected 282.35 GiB'), ('050', '050 - Unprotected Variable')], help_text='OS/400 volume type for iSeries (FB only). When set, uses -os400 parameter.', max_length=3, null=True),
        ),
    ]
