# Generated by Django 5.1.6 on 2026-01-04 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_pprc_path_models'),
        ('storage', '0017_add_volume_capacity_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PPRCPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('committed', models.BooleanField(default=False, help_text='Changes approved/finalized')),
                ('deployed', models.BooleanField(default=False, help_text='Actually deployed to infrastructure')),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=0, help_text='Version number for optimistic locking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_project', models.ForeignKey(blank=True, help_text='Project that originally created this entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pprc_paths', to='core.project')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='User who last modified this PPRC path', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_pprc_paths', to=settings.AUTH_USER_MODEL)),
                ('port1', models.ForeignKey(help_text='First port in the PPRC path (lower ID)', on_delete=django.db.models.deletion.CASCADE, related_name='pprc_paths_as_port1', to='storage.port')),
                ('port2', models.ForeignKey(help_text='Second port in the PPRC path (higher ID)', on_delete=django.db.models.deletion.CASCADE, related_name='pprc_paths_as_port2', to='storage.port')),
            ],
            options={
                'verbose_name': 'PPRC Path',
                'verbose_name_plural': 'PPRC Paths',
                'ordering': ['port1__storage', 'port1__name', 'port2__name'],
                'indexes': [models.Index(fields=['port1', 'port2'], name='storage_ppr_port1_i_612794_idx')],
                'unique_together': {('port1', 'port2')},
            },
        ),
    ]
