# Generated by Django 5.1.6 on 2026-01-04 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_pprc_replication_groups'),
        ('storage', '0018_add_pprc_path_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PPRCReplicationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.PositiveIntegerField(default=1, help_text='Group number (1 is default)')),
                ('name', models.CharField(blank=True, help_text='Optional friendly name for the group', max_length=100)),
                ('lss_mode', models.CharField(choices=[('all', 'All LSSs'), ('custom', 'Custom LSSs')], default='all', help_text="'all' = all LSSs; 'custom' = specific LSSs only", max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('committed', models.BooleanField(default=False, help_text='Changes approved/finalized')),
                ('deployed', models.BooleanField(default=False, help_text='Actually deployed to infrastructure')),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=0, help_text='Version number for optimistic locking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_project', models.ForeignKey(blank=True, help_text='Project that originally created this entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pprc_groups', to='core.project')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='User who last modified this replication group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_pprc_groups', to=settings.AUTH_USER_MODEL)),
                ('source_storage', models.ForeignKey(help_text='Source DS8000 storage system', on_delete=django.db.models.deletion.CASCADE, related_name='pprc_groups_as_source', to='storage.storage')),
                ('target_storage', models.ForeignKey(help_text='Target DS8000 storage system', on_delete=django.db.models.deletion.CASCADE, related_name='pprc_groups_as_target', to='storage.storage')),
            ],
            options={
                'verbose_name': 'PPRC Replication Group',
                'verbose_name_plural': 'PPRC Replication Groups',
                'ordering': ['source_storage', 'target_storage', 'group_number'],
                'unique_together': {('source_storage', 'target_storage', 'group_number')},
            },
        ),
        migrations.AddField(
            model_name='pprcpath',
            name='replication_group',
            field=models.ForeignKey(blank=True, help_text='Replication group this path belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paths', to='storage.pprcreplicationgroup'),
        ),
        migrations.CreateModel(
            name='PPRCGroupLSSMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_lss', models.CharField(help_text="Source LSS (2 hex digits, e.g., '50')", max_length=2)),
                ('target_lss', models.CharField(help_text="Target LSS (2 hex digits, e.g., '60')", max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lss_mappings', to='storage.pprcreplicationgroup')),
            ],
            options={
                'verbose_name': 'PPRC Group LSS Mapping',
                'verbose_name_plural': 'PPRC Group LSS Mappings',
                'ordering': ['source_lss'],
                'unique_together': {('group', 'source_lss')},
            },
        ),
    ]
