# Generated by Django 5.1.6 on 2026-01-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0019_add_pprc_replication_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pprcreplicationgroup',
            name='lss_mode',
            field=models.CharField(choices=[('all', 'All LSSs'), ('custom', 'Custom LSSs'), ('even', 'Even LSSs'), ('odd', 'Odd LSSs')], default='all', help_text="'all' = all LSSs; 'custom' = specific LSSs only", max_length=10),
        ),
    ]
