# Generated by Django 5.1.6 on 2025-02-23 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('zoneset_name', models.CharField(max_length=200)),
                ('vsan', models.IntegerField(blank=True, null=True)),
                ('exists', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrics', to='core.project')),
                ('users', models.ManyToManyField(related_name='fabric_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wwpn', models.CharField(max_length=23)),
                ('use', models.CharField(blank=True, choices=[('init', 'Initiator'), ('target', 'Target'), ('both', 'Both')], max_length=6, null=True)),
                ('create', models.BooleanField(default=False)),
                ('include_in_zoning', models.BooleanField(default=False)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alias_host', to='storage.host')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='storage.storage')),
                ('users', models.ManyToManyField(related_name='alias_users', to=settings.AUTH_USER_MODEL)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san.fabric')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('fabric', 'name'), ('fabric', 'wwpn')},
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create', models.BooleanField(default=False)),
                ('exists', models.BooleanField(default=False)),
                ('zone_type', models.CharField(choices=[('smart', 'smart'), ('standard', 'standard')], max_length=100)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san.fabric')),
                ('members', models.ManyToManyField(to='san.alias')),
                ('users', models.ManyToManyField(related_name='zone_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create', models.BooleanField(default=False)),
                ('zone_type', models.CharField(choices=[('smart', 'smart'), ('standard', 'standard')], max_length=100)),
                ('exists', models.BooleanField(default=False)),
                ('aliases', models.ManyToManyField(to='san.alias')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san.fabric')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storage')),
                ('users', models.ManyToManyField(related_name='zonegroup_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
