# Generated by Django 5.1.6 on 2025-10-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('insights_api_key', models.CharField(blank=True, max_length=600, null=True)),
                ('insights_tenant', models.CharField(blank=True, max_length=200, null=True)),
                ('projects', models.ManyToManyField(blank=True, related_name='customers', to='core.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
