# Generated by Django 5.1.6 on 2025-03-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_config_active_project_alter_config_cisco_alias_and_more'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='projects',
            field=models.ManyToManyField(related_name='customers', to='core.project'),
        ),
    ]
