# Generated by Django 5.1.6 on 2025-10-21 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Contact person's full name", max_length=200)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=50, null=True)),
                ('title', models.CharField(blank=True, help_text="Contact's job title or role", max_length=200, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Use this contact as default for worksheets and reports')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this contact', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer this contact belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'ordering': ['-is_default', 'name'],
                'indexes': [models.Index(fields=['customer', 'is_default'], name='customers_c_custome_ba252f_idx')],
            },
        ),
    ]
