# Generated by Django 5.1.6 on 2025-10-21 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer this contact belongs to (leave blank for global implementation team contacts)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='customers.customer'),
        ),
    ]
