# Generated by Django 5.1.6 on 2025-04-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='insights_api_key',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='insights_tenant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
