# Generated by Django 5.1.6 on 2025-10-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_contactinfo_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_implementation_company',
            field=models.BooleanField(default=False, help_text='Mark this as the implementation company (e.g., Evolving Solutions). Only one can be active.'),
        ),
    ]
