# Generated by Django 5.1.6 on 2025-04-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_notes'),
        ('customers', '0004_customer_insights_api_key_customer_insights_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='customers', to='core.project'),
        ),
    ]
