# Generated by Django 5.1.6 on 2025-06-04 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APICredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('tenant_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'API Credentials',
            },
        ),
        migrations.CreateModel(
            name='DataMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(default='storage_insights', max_length=50)),
                ('local_model', models.CharField(max_length=100)),
                ('local_field', models.CharField(max_length=100)),
                ('api_field_path', models.CharField(max_length=200)),
                ('transformation_rule', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('local_model', 'local_field', 'api_field_path')},
            },
        ),
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=100)),
                ('last_imported', models.DateTimeField()),
                ('last_modified_api', models.DateTimeField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('local_object_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['resource_type', 'last_imported'], name='insights_im_resourc_c5b34e_idx')],
                'unique_together': {('resource_type', 'resource_id')},
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=50, unique=True)),
                ('job_type', models.CharField(choices=[('full', 'Full Import'), ('incremental', 'Incremental Import'), ('storage_only', 'Storage Systems Only'), ('volumes_only', 'Volumes Only'), ('hosts_only', 'Hosts Only')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('error_details', models.TextField(blank=True)),
                ('api_credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights_importer.apicredentials')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='insights_importer.importjob')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
