# Generated by Django 5.1.6 on 2025-06-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights_importer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
