# Generated by Django 5.1.6 on 2025-10-13 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insights_tenant', models.CharField(help_text='IBM Storage Insights tenant ID', max_length=100)),
                ('insights_api_key', models.CharField(help_text='IBM Storage Insights API key', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_credentials', to='customers.customer')),
            ],
            options={
                'verbose_name': 'API Credentials',
                'verbose_name_plural': 'API Credentials',
            },
        ),
        migrations.CreateModel(
            name='StorageImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for background processing', max_length=255, null=True)),
                ('storage_systems_imported', models.IntegerField(default=0)),
                ('volumes_imported', models.IntegerField(default=0)),
                ('hosts_imported', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, help_text='Error details if import failed')),
                ('api_response_summary', models.JSONField(blank=True, help_text='Summary of API responses', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_imports', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Storage Import',
                'verbose_name_plural': 'Storage Imports',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, help_text='Additional structured data', null=True)),
                ('import_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='importer.storageimport')),
            ],
            options={
                'verbose_name': 'Import Log',
                'verbose_name_plural': 'Import Logs',
                'ordering': ['timestamp'],
            },
        ),
    ]
