# Generated by Django 5.1.6 on 2025-10-28 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storageimport',
            name='cancelled',
            field=models.BooleanField(default=False, help_text='Flag to request cancellation of running import'),
        ),
        migrations.AddField(
            model_name='storageimport',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the import was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='storageimport',
            name='import_name',
            field=models.CharField(blank=True, help_text='Optional user-provided name for this import', max_length=255),
        ),
        migrations.AddField(
            model_name='storageimport',
            name='import_type',
            field=models.CharField(blank=True, choices=[('san_config', 'SAN Configuration'), ('storage_insights', 'IBM Storage Insights')], help_text='Type of import', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='storageimport',
            name='initiated_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated this import', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storageimport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
