apiVersion: v1
kind: List
metadata:
  name: sanbox-routes
items:
  # Main application route (frontend)
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: sanbox
      labels:
        app: sanbox
        component: nginx
      annotations:
        haproxy.router.openshift.io/timeout: 120s
    spec:
      to:
        kind: Service
        name: nginx
        weight: 100
      port:
        targetPort: http
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None

  # API-specific route (optional, for direct API access)
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: sanbox-api
      labels:
        app: sanbox
        component: backend
      annotations:
        haproxy.router.openshift.io/timeout: 300s
    spec:
      path: /api
      to:
        kind: Service
        name: backend
        weight: 100
      port:
        targetPort: http
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
