# Generated by Django 5.1.6 on 2025-07-31 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('san_vendor', models.CharField(choices=[('BR', 'Brocade'), ('CI', 'Cisco')], default='BR', max_length=7)),
                ('cisco_alias', models.CharField(choices=[('device-alias', 'device-alias'), ('fcalias', 'fcalias'), ('wwpn', 'wwpn')], default='device-alias', max_length=15)),
                ('cisco_zoning_mode', models.CharField(choices=[('basic', 'basic'), ('enhanced', 'enhanced')], default='enhanced', max_length=15)),
                ('zone_ratio', models.CharField(choices=[('one-to-one', 'one-to-one'), ('one-to-many', 'one-to-many'), ('all-to-all', 'all-to-all')], default='one-to-one', max_length=20)),
                ('zoning_job_name', models.CharField(default='default_job', max_length=40)),
                ('alias_max_zones', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(help_text="Name of the table (e.g., 'storage', 'volumes', 'hosts', 'zones', 'aliases')", max_length=100)),
                ('visible_columns', models.JSONField(blank=True, default=list, help_text='List of visible column names/keys in order')),
                ('column_widths', models.JSONField(blank=True, default=dict, help_text='Dictionary mapping column names to their widths')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Active filters as key-value pairs')),
                ('sorting', models.JSONField(blank=True, default=dict, help_text='Sorting configuration (column, direction)')),
                ('page_size', models.IntegerField(default=25, help_text='Number of rows per page')),
                ('additional_settings', models.JSONField(blank=True, default=dict, help_text='Any additional table-specific settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Table Configuration',
                'verbose_name_plural': 'Table Configurations',
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (System)')], default='light', help_text='UI theme preference', max_length=10)),
                ('items_per_page', models.IntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100')], default=25, help_text='Default number of items per page in tables')),
                ('compact_mode', models.BooleanField(default=False, help_text='Enable compact mode for tables and UI elements')),
                ('auto_refresh', models.BooleanField(default=True, help_text='Enable automatic data refresh')),
                ('auto_refresh_interval', models.IntegerField(choices=[(15, '15 seconds'), (30, '30 seconds'), (60, '1 minute'), (300, '5 minutes')], default=30, help_text='Auto-refresh interval in seconds')),
                ('notifications', models.BooleanField(default=True, help_text='Enable browser notifications')),
                ('show_advanced_features', models.BooleanField(default=False, help_text='Show advanced features and debugging tools')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='User these settings belong to (null for global defaults)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
