# Generated by Django 5.1.6 on 2025-04-29 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='config',
            name='active_project',
            field=models.ForeignKey(blank=True, help_text="The currently active project for this customer's config.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_configs', to='core.project'),
        ),
    ]
