# Generated by Django 5.1.6 on 2025-07-31 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='config',
            name='active_project',
            field=models.ForeignKey(blank=True, help_text="The currently active project for this customer's config.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_configs', to='core.project'),
        ),
        migrations.AddField(
            model_name='tableconfiguration',
            name='customer',
            field=models.ForeignKey(help_text='Customer this configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='table_configurations', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='tableconfiguration',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User this configuration belongs to (optional for global settings)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_configurations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='appsettings',
            index=models.Index(fields=['user'], name='core_appset_user_id_d5148f_idx'),
        ),
        migrations.AddIndex(
            model_name='tableconfiguration',
            index=models.Index(fields=['customer', 'table_name'], name='core_tablec_custome_ca088f_idx'),
        ),
        migrations.AddIndex(
            model_name='tableconfiguration',
            index=models.Index(fields=['user', 'table_name'], name='core_tablec_user_id_debdd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tableconfiguration',
            unique_together={('customer', 'user', 'table_name')},
        ),
    ]
