# Generated by Django 5.1.6 on 2025-03-12 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['customer', 'name']},
        ),
    ]
