# Generated by Django 5.1.6 on 2025-03-13 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_options'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='project',
        ),
        migrations.AddField(
            model_name='config',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='config', to='customers.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
