# Generated by Django 5.1.6 on 2025-07-23 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(help_text="Name of the table (e.g., 'storage', 'volumes', 'hosts', 'zones', 'aliases')", max_length=100)),
                ('visible_columns', models.JSONField(blank=True, default=list, help_text='List of visible column names/keys in order')),
                ('column_widths', models.JSONField(blank=True, default=dict, help_text='Dictionary mapping column names to their widths')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Active filters as key-value pairs')),
                ('sorting', models.JSONField(blank=True, default=dict, help_text='Sorting configuration (column, direction)')),
                ('page_size', models.IntegerField(default=25, help_text='Number of rows per page')),
                ('additional_settings', models.JSONField(blank=True, default=dict, help_text='Any additional table-specific settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer this configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='table_configurations', to='customers.customer')),
                ('user', models.ForeignKey(blank=True, help_text='User this configuration belongs to (optional for global settings)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Table Configuration',
                'verbose_name_plural': 'Table Configurations',
                'indexes': [models.Index(fields=['customer', 'table_name'], name='core_tablec_custome_ca088f_idx'), models.Index(fields=['user', 'table_name'], name='core_tablec_user_id_debdd7_idx')],
                'unique_together': {('customer', 'user', 'table_name')},
            },
        ),
    ]
