# Generated by Django 5.1.6 on 2025-07-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='alias_max_zones',
        ),
        migrations.RemoveField(
            model_name='config',
            name='cisco_alias',
        ),
        migrations.RemoveField(
            model_name='config',
            name='cisco_zoning_mode',
        ),
        migrations.RemoveField(
            model_name='config',
            name='san_vendor',
        ),
        migrations.RemoveField(
            model_name='config',
            name='zone_ratio',
        ),
        migrations.RemoveField(
            model_name='config',
            name='zoning_job_name',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='alias_max_zones',
            field=models.IntegerField(default=1, help_text='Maximum number of zones per alias'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='zone_ratio',
            field=models.CharField(choices=[('one-to-one', 'one-to-one'), ('one-to-many', 'one-to-many'), ('all-to-all', 'all-to-all')], default='one-to-one', help_text='Default zone ratio for SAN operations', max_length=20),
        ),
    ]
