# Generated by Django 5.1.6 on 2025-10-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_make_table_config_user_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableconfiguration',
            name='page_size',
            field=models.CharField(default='25', help_text="Number of rows per page (numeric value or 'All')", max_length=10),
        ),
    ]
