# Generated by Django 5.1.6 on 2025-03-06 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_examplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
