# Generated by Django 5.1.6 on 2025-03-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_config_project_config_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='config',
            name='cisco_alias',
            field=models.CharField(blank=True, choices=[('device-alias', 'device-alias'), ('fcalias', 'fcalias'), ('wwpn', 'wwpn')], default='device-alias', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='san_vendor',
            field=models.CharField(blank=True, choices=[('BR', 'Brocade'), ('CI', 'Cisco')], default='BR', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='zoning_job_name',
            field=models.CharField(blank=True, default='default_job', max_length=40, null=True),
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer',
        ),
    ]
