# Generated by Django 5.1.6 on 2025-10-21 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_change_page_size_to_charfield'),
        ('customers', '0002_contactinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Equipment type name (e.g., 'SAN Switch', 'FlashSystem')", max_length=200, unique=True)),
                ('category', models.CharField(choices=[('storage', 'Storage'), ('network', 'Network'), ('compute', 'Compute'), ('backup', 'Backup'), ('other', 'Other')], help_text='Equipment category for grouping', max_length=50)),
                ('vendor', models.CharField(blank=True, help_text='Primary vendor for this equipment type (optional)', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of this equipment type', null=True)),
                ('fields_schema', models.JSONField(default=list, help_text='Dynamic fields for this equipment type. Format:\n        [{"name": "field_name", "label": "Field Label", "type": "text|number|select|date",\n          "required": true/false, "options": [] (for select type)}]')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this equipment type is available for selection')),
                ('icon_name', models.CharField(blank=True, help_text="Icon name from react-icons (e.g., 'FaServer', 'FaHdd')", max_length=100, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Display order in the equipment selector')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment Type',
                'verbose_name_plural': 'Equipment Types',
                'ordering': ['category', 'display_order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='core_equipm_categor_2c87e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorksheetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of this template', null=True)),
                ('template_config', models.JSONField(default=dict, help_text='Template configuration including equipment quantities and field values.\n        Format: {"equipment": [{"type_id": 1, "quantity": 2, "fields": {...}}]}')),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this customer/user')),
                ('is_global', models.BooleanField(default=False, help_text='Available to all users (admin-created templates)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Customer this template belongs to (null for global templates)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_templates', to='customers.customer')),
                ('equipment_types', models.ManyToManyField(help_text='Equipment types included in this template', related_name='worksheet_templates', to='core.equipmenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who created this template (null for global templates)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worksheet Template',
                'verbose_name_plural': 'Worksheet Templates',
                'ordering': ['-is_default', '-is_global', 'name'],
                'indexes': [models.Index(fields=['customer', 'user'], name='core_worksh_custome_31412d_idx'), models.Index(fields=['is_global', 'is_default'], name='core_worksh_is_glob_592263_idx')],
            },
        ),
    ]
