# Generated by Django 5.1.6 on 2025-03-13 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_options_alter_project_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='active_project',
            field=models.ForeignKey(blank=True, help_text="The currently active project for this customer's config.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_configs', to='core.project'),
        ),
        migrations.AlterField(
            model_name='config',
            name='cisco_alias',
            field=models.CharField(choices=[('device-alias', 'device-alias'), ('fcalias', 'fcalias'), ('wwpn', 'wwpn')], default='device-alias', max_length=15),
        ),
        migrations.AlterField(
            model_name='config',
            name='san_vendor',
            field=models.CharField(choices=[('BR', 'Brocade'), ('CI', 'Cisco')], default='BR', max_length=7),
        ),
        migrations.AlterField(
            model_name='config',
            name='zoning_job_name',
            field=models.CharField(default='default_job', max_length=40),
        ),
    ]
