# Generated by Django 5.1.6 on 2025-07-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_appsettings_items_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='items_per_page',
            field=models.IntegerField(choices=[(25, '25'), (50, '50'), (100, '100'), (250, '250')], default=50, help_text='Default number of items per page in tables'),
        ),
    ]
