# Generated by Django 5.1.6 on 2025-03-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_examplemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='smartzone_prefix',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
