# Generated by Django 5.1.6 on 2025-08-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_appsettings_items_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='host_max_aliases',
            field=models.IntegerField(default=10, help_text='Maximum number of aliases that can be assigned to each host'),
        ),
    ]
