# Generated by Django 5.1.6 on 2025-10-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_equipmenttype_worksheettemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='new_users_are_staff',
            field=models.BooleanField(default=True, help_text='Automatically grant staff status (Django admin access) to newly registered users'),
        ),
    ]
