# Generated by Django 5.1.6 on 2025-08-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appsettings_host_max_aliases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='host_max_aliases',
        ),
    ]
