# Generated by Django 5.1.6 on 2025-10-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appsettings_new_users_are_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='new_users_are_superuser',
            field=models.BooleanField(default=True, help_text='Automatically grant superuser status (full admin privileges) to newly registered users'),
        ),
    ]
