# Generated by Django 5.1.6 on 2025-04-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='smartzone_prefix',
        ),
    ]
