# Generated by Django 5.1.6 on 2025-10-23 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appsettings_new_users_are_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardAnalytics',
        ),
    ]
