# Generated by Django 5.1.6 on 2025-09-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_appsettings_host_max_aliases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='items_per_page',
            field=models.CharField(choices=[('25', '25'), ('50', '50'), ('100', '100'), ('250', '250'), ('All', 'All')], default='All', help_text='Default number of items per page in tables', max_length=10),
        ),
    ]
