# Generated by Django 5.1.6 on 2025-09-10 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_all_option_to_items_per_page'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNamingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this naming rule', max_length=100)),
                ('table_name', models.CharField(help_text="Target table name (e.g., 'zones', 'aliases', 'storage')", max_length=100)),
                ('pattern', models.JSONField(help_text='Naming pattern as array of objects with type and value')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer this naming rule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='custom_naming_rules', to='customers.customer')),
                ('user', models.ForeignKey(blank=True, help_text='User this naming rule belongs to (optional for global rules)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_naming_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Naming Rule',
                'verbose_name_plural': 'Custom Naming Rules',
                'indexes': [models.Index(fields=['customer', 'table_name'], name='core_custom_custome_46b00d_idx'), models.Index(fields=['user', 'table_name'], name='core_custom_user_id_c9c928_idx')],
                'unique_together': {('customer', 'user', 'name', 'table_name')},
            },
        ),
        migrations.CreateModel(
            name='CustomVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Variable name (e.g., 'environment', 'datacenter')", max_length=100)),
                ('value', models.CharField(help_text="Variable value (e.g., 'prod', 'dc1')", max_length=200)),
                ('description', models.CharField(blank=True, help_text='Optional description of what this variable represents', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer this variable belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='custom_variables', to='customers.customer')),
                ('user', models.ForeignKey(blank=True, help_text='User this variable belongs to (optional for global variables)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_variables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Variable',
                'verbose_name_plural': 'Custom Variables',
                'indexes': [models.Index(fields=['customer', 'name'], name='core_custom_custome_2982d1_idx'), models.Index(fields=['user', 'name'], name='core_custom_user_id_fbd255_idx')],
                'unique_together': {('customer', 'user', 'name')},
            },
        ),
    ]
