# Generated by Django 5.1.6 on 2025-10-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_dashboardanalytics'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectgroup',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='projectgroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectgroup',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='projectgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='project',
            name='group',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='visibility',
        ),
        migrations.AddField(
            model_name='userconfig',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True, help_text='Last activity timestamp for presence detection'),
        ),
        migrations.DeleteModel(
            name='CustomerMembership',
        ),
        migrations.DeleteModel(
            name='ProjectGroup',
        ),
    ]
