# Generated by Django 5.1.6 on 2025-10-29 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_dashboard_widgets'),
        ('customers', '0004_customer_is_implementation_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='audit_log_retention_days',
            field=models.IntegerField(default=90, help_text='Number of days to retain audit logs before automatic purge'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action was initiated')),
                ('action_type', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('IMPORT', 'Data Import'), ('BACKUP', 'Database Backup'), ('RESTORE', 'Database Restore'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('EXPORT', 'Data Export'), ('CONFIG_CHANGE', 'Configuration Change')], db_index=True, help_text='Type of action performed', max_length=20)),
                ('entity_type', models.CharField(blank=True, choices=[('FABRIC', 'Fabric'), ('ZONE', 'Zone'), ('ALIAS', 'Alias'), ('SWITCH', 'Switch'), ('STORAGE_SYSTEM', 'Storage System'), ('VOLUME', 'Volume'), ('HOST', 'Host'), ('BACKUP', 'Backup'), ('CREDENTIALS', 'Credentials'), ('SETTINGS', 'Settings'), ('USER', 'User')], help_text='Type of entity affected', max_length=20, null=True)),
                ('entity_name', models.CharField(blank=True, help_text='Name of specific entity affected (optional)', max_length=255, null=True)),
                ('summary', models.TextField(help_text='Human-readable summary of the action')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Structured data about the action (counts, errors, etc.)')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SUCCESS', help_text='Status of the action', max_length=15)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Duration of the action in seconds', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Customer this action affects', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='customers.customer')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_auditl_timesta_189a84_idx'), models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_2a1528_idx'), models.Index(fields=['customer', '-timestamp'], name='core_auditl_custome_7783ca_idx'), models.Index(fields=['action_type', '-timestamp'], name='core_auditl_action__f8907a_idx'), models.Index(fields=['status', '-timestamp'], name='core_auditl_status_ec49d2_idx')],
            },
        ),
    ]
