# Generated by Django 5.1.6 on 2025-09-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_make_custom_naming_global'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customnamingrule',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customvariable',
            name='customer',
        ),
    ]
