# Generated by Django 5.1.6 on 2025-09-12 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_customer_field_from_naming'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customnamingrule',
            name='core_custom_table_n_ab3189_idx',
        ),
        migrations.RemoveIndex(
            model_name='customnamingrule',
            name='core_custom_is_acti_9791a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='customvariable',
            name='core_custom_name_244b9a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='customnamingrule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='customvariable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customnamingrule',
            name='customer',
            field=models.ForeignKey(default=25, help_text='Customer this naming rule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='custom_naming_rules', to='customers.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customvariable',
            name='customer',
            field=models.ForeignKey(default=25, help_text='Customer this variable belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='custom_variables', to='customers.customer'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='customnamingrule',
            unique_together={('customer', 'user', 'name', 'table_name')},
        ),
        migrations.AlterUniqueTogether(
            name='customvariable',
            unique_together={('customer', 'user', 'name')},
        ),
        migrations.AddIndex(
            model_name='customnamingrule',
            index=models.Index(fields=['customer', 'table_name'], name='core_custom_custome_46b00d_idx'),
        ),
        migrations.AddIndex(
            model_name='customvariable',
            index=models.Index(fields=['customer', 'name'], name='core_custom_custome_2982d1_idx'),
        ),
    ]
