# Generated by Django 5.1.6 on 2025-09-20 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_customnamingrule_core_custom_table_n_ab3189_idx_and_more'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('executive', 'Executive Overview'), ('technical', 'Technical Operations'), ('capacity', 'Capacity Planning'), ('security', 'Security Monitoring'), ('performance', 'Performance Analytics'), ('custom', 'Custom Templates')], max_length=50)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('layout_config', models.JSONField()),
                ('required_permissions', models.JSONField(default=list)),
                ('target_roles', models.JSONField(default=list)),
                ('is_system', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-usage_count', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('css_variables', models.JSONField(default=dict)),
                ('background_type', models.CharField(choices=[('solid', 'Solid Color'), ('gradient', 'Gradient'), ('pattern', 'Pattern'), ('image', 'Background Image')], default='solid', max_length=20)),
                ('background_config', models.JSONField(default=dict)),
                ('card_style', models.CharField(choices=[('modern', 'Modern Cards'), ('flat', 'Flat Design'), ('glass', 'Glassmorphism'), ('neumorphism', 'Neumorphism'), ('minimal', 'Minimal Borders')], default='modern', max_length=20)),
                ('animation_level', models.CharField(choices=[('none', 'No Animations'), ('minimal', 'Minimal'), ('medium', 'Medium'), ('full', 'Full Animations')], default='medium', max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('endpoint_pattern', models.CharField(max_length=500)),
                ('parameters_schema', models.JSONField(default=dict)),
                ('cache_duration', models.IntegerField(default=300)),
                ('requires_auth', models.BooleanField(default=True)),
                ('data_format', models.CharField(default='json', max_length=50)),
                ('is_real_time', models.BooleanField(default=False)),
                ('update_frequency', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('component_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('metrics', 'Key Metrics'), ('charts', 'Charts & Graphs'), ('tables', 'Data Tables'), ('health', 'System Health'), ('activity', 'Activity & Logs'), ('tools', 'Quick Tools'), ('custom', 'Custom Widgets')], max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('default_width', models.IntegerField(default=4)),
                ('default_height', models.IntegerField(default=300)),
                ('min_width', models.IntegerField(default=2)),
                ('min_height', models.IntegerField(default=200)),
                ('max_width', models.IntegerField(default=12)),
                ('max_height', models.IntegerField(default=800)),
                ('is_resizable', models.BooleanField(default=True)),
                ('requires_data_source', models.BooleanField(default=True)),
                ('config_schema', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Dashboard', max_length=255)),
                ('theme', models.CharField(choices=[('modern', 'Modern'), ('dark', 'Dark Mode'), ('minimal', 'Minimal'), ('corporate', 'Corporate'), ('colorful', 'Colorful')], default='modern', max_length=50)),
                ('grid_columns', models.IntegerField(default=12)),
                ('auto_refresh', models.BooleanField(default=True)),
                ('refresh_interval', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layout', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=4)),
                ('height', models.IntegerField(default=300)),
                ('config', models.JSONField(default=dict)),
                ('data_filters', models.JSONField(default=dict)),
                ('refresh_interval', models.IntegerField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('z_index', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='core.dashboardlayout')),
                ('widget_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.widgettype')),
            ],
            options={
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='DashboardAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'Dashboard View'), ('widget_add', 'Widget Added'), ('widget_remove', 'Widget Removed'), ('widget_resize', 'Widget Resized'), ('widget_move', 'Widget Moved'), ('config_change', 'Configuration Changed'), ('theme_change', 'Theme Changed'), ('export', 'Data Export'), ('refresh', 'Manual Refresh')], max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dashboardlayout')),
                ('widget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dashboardwidget')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['layout', 'event_type', 'timestamp'], name='core_dashbo_layout__632acc_idx'), models.Index(fields=['widget', 'event_type', 'timestamp'], name='core_dashbo_widget__6333b2_idx')],
            },
        ),
    ]
