# Generated by Django 5.1.6 on 2025-11-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_create_action_to_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectalias',
            name='action',
            field=models.CharField(choices=[('new', 'New - Generate creation commands'), ('delete', 'Delete - Generate deletion commands'), ('modify', 'Modify - Generate modification commands'), ('reference', 'Reference - Include in documentation only')], default='reference', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectfabric',
            name='action',
            field=models.CharField(choices=[('new', 'New - Generate creation commands'), ('delete', 'Delete - Generate deletion commands'), ('modify', 'Modify - Generate modification commands'), ('reference', 'Reference - Include in documentation only')], default='reference', max_length=10),
        ),
        migrations.AlterField(
            model_name='projecthost',
            name='action',
            field=models.CharField(choices=[('new', 'New - Generate creation commands'), ('delete', 'Delete - Generate deletion commands'), ('modify', 'Modify - Generate modification commands'), ('reference', 'Reference - Include in documentation only')], default='reference', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectport',
            name='action',
            field=models.CharField(choices=[('new', 'New - Generate creation commands'), ('delete', 'Delete - Generate deletion commands'), ('modify', 'Modify - Generate modification commands'), ('reference', 'Reference - Include in documentation only')], default='reference', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectstorage',
            name='action',
            field=models.CharField(choices=[('new', 'New - Generate creation commands'), ('delete', 'Delete - Generate deletion commands'), ('modify', 'Modify - Generate modification commands'), ('reference', 'Reference - Include in documentation only')], default='reference', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectswitch',
            name='action',
            field=models.CharField(choices=[('new', 'New - Generate creation commands'), ('delete', 'Delete - Generate deletion commands'), ('modify', 'Modify - Generate modification commands'), ('reference', 'Reference - Include in documentation only')], default='reference', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectvolume',
            name='action',
            field=models.CharField(choices=[('new', 'New - Generate creation commands'), ('delete', 'Delete - Generate deletion commands'), ('modify', 'Modify - Generate modification commands'), ('reference', 'Reference - Include in documentation only')], default='reference', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectzone',
            name='action',
            field=models.CharField(choices=[('new', 'New - Generate creation commands'), ('delete', 'Delete - Generate deletion commands'), ('modify', 'Modify - Generate modification commands'), ('reference', 'Reference - Include in documentation only')], default='reference', max_length=10),
        ),
    ]
