# Generated by Django 5.1.6 on 2025-11-07 21:22

from django.db import migrations, models


def migrate_delete_actions(apps, schema_editor):
    """Convert existing action='delete' records to action='unmodified' and delete_me=True"""

    # Get all junction table models
    ProjectAlias = apps.get_model('core', 'ProjectAlias')
    ProjectZone = apps.get_model('core', 'ProjectZone')
    ProjectFabric = apps.get_model('core', 'ProjectFabric')
    ProjectSwitch = apps.get_model('core', 'ProjectSwitch')
    ProjectStorage = apps.get_model('core', 'ProjectStorage')
    ProjectVolume = apps.get_model('core', 'ProjectVolume')
    ProjectHost = apps.get_model('core', 'ProjectHost')
    ProjectPort = apps.get_model('core', 'ProjectPort')

    # Update each table
    for Model in [ProjectAlias, ProjectZone, ProjectFabric, ProjectSwitch,
                  ProjectStorage, ProjectVolume, ProjectHost, ProjectPort]:
        Model.objects.filter(action='delete').update(
            action='unmodified',
            delete_me=True
        )


def reverse_migrate_delete_actions(apps, schema_editor):
    """Reverse the migration by converting delete_me=True back to action='delete'"""

    # Get all junction table models
    ProjectAlias = apps.get_model('core', 'ProjectAlias')
    ProjectZone = apps.get_model('core', 'ProjectZone')
    ProjectFabric = apps.get_model('core', 'ProjectFabric')
    ProjectSwitch = apps.get_model('core', 'ProjectSwitch')
    ProjectStorage = apps.get_model('core', 'ProjectStorage')
    ProjectVolume = apps.get_model('core', 'ProjectVolume')
    ProjectHost = apps.get_model('core', 'ProjectHost')
    ProjectPort = apps.get_model('core', 'ProjectPort')

    # Update each table
    for Model in [ProjectAlias, ProjectZone, ProjectFabric, ProjectSwitch,
                  ProjectStorage, ProjectVolume, ProjectHost, ProjectPort]:
        Model.objects.filter(delete_me=True).update(
            action='delete',
            delete_me=False
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_projectalias_action_alter_projectfabric_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectalias',
            name='delete_me',
            field=models.BooleanField(default=False, help_text='Mark this item for deletion (overrides action for display)'),
        ),
        migrations.AddField(
            model_name='projectfabric',
            name='delete_me',
            field=models.BooleanField(default=False, help_text='Mark this item for deletion (overrides action for display)'),
        ),
        migrations.AddField(
            model_name='projecthost',
            name='delete_me',
            field=models.BooleanField(default=False, help_text='Mark this item for deletion (overrides action for display)'),
        ),
        migrations.AddField(
            model_name='projectport',
            name='delete_me',
            field=models.BooleanField(default=False, help_text='Mark this item for deletion (overrides action for display)'),
        ),
        migrations.AddField(
            model_name='projectstorage',
            name='delete_me',
            field=models.BooleanField(default=False, help_text='Mark this item for deletion (overrides action for display)'),
        ),
        migrations.AddField(
            model_name='projectswitch',
            name='delete_me',
            field=models.BooleanField(default=False, help_text='Mark this item for deletion (overrides action for display)'),
        ),
        migrations.AddField(
            model_name='projectvolume',
            name='delete_me',
            field=models.BooleanField(default=False, help_text='Mark this item for deletion (overrides action for display)'),
        ),
        migrations.AddField(
            model_name='projectzone',
            name='delete_me',
            field=models.BooleanField(default=False, help_text='Mark this item for deletion (overrides action for display)'),
        ),
        # Convert existing action='delete' records to use delete_me flag
        migrations.RunPython(
            migrate_delete_actions,
            reverse_code=reverse_migrate_delete_actions
        ),
        migrations.AlterField(
            model_name='projectalias',
            name='action',
            field=models.CharField(choices=[('new', 'Created in this project'), ('modified', 'Existed but modified in this project'), ('unmodified', 'Existed and has not been modified in this project')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectfabric',
            name='action',
            field=models.CharField(choices=[('new', 'Created in this project'), ('modified', 'Existed but modified in this project'), ('unmodified', 'Existed and has not been modified in this project')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='projecthost',
            name='action',
            field=models.CharField(choices=[('new', 'Created in this project'), ('modified', 'Existed but modified in this project'), ('unmodified', 'Existed and has not been modified in this project')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectport',
            name='action',
            field=models.CharField(choices=[('new', 'Created in this project'), ('modified', 'Existed but modified in this project'), ('unmodified', 'Existed and has not been modified in this project')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectstorage',
            name='action',
            field=models.CharField(choices=[('new', 'Created in this project'), ('modified', 'Existed but modified in this project'), ('unmodified', 'Existed and has not been modified in this project')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectswitch',
            name='action',
            field=models.CharField(choices=[('new', 'Created in this project'), ('modified', 'Existed but modified in this project'), ('unmodified', 'Existed and has not been modified in this project')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectvolume',
            name='action',
            field=models.CharField(choices=[('new', 'Created in this project'), ('modified', 'Existed but modified in this project'), ('unmodified', 'Existed and has not been modified in this project')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectzone',
            name='action',
            field=models.CharField(choices=[('new', 'Created in this project'), ('modified', 'Existed but modified in this project'), ('unmodified', 'Existed and has not been modified in this project')], default='new', max_length=10),
        ),
    ]
