# Generated by Django 5.1.6 on 2025-09-24 18:10

from django.db import migrations, models


def migrate_app_settings_theme(apps, schema_editor):
    """Migrate any 'auto' theme values to 'light'"""
    AppSettings = apps.get_model('core', 'AppSettings')
    
    # Convert 'auto' theme values to 'light'
    AppSettings.objects.filter(theme='auto').update(theme='light')


def reverse_migrate_app_settings_theme(apps, schema_editor):
    """Reverse migration - no need to restore 'auto' values"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20250924_1617'),
    ]

    operations = [
        # First migrate the data
        migrations.RunPython(migrate_app_settings_theme, reverse_migrate_app_settings_theme),
        
        # Then update the field choices
        migrations.AlterField(
            model_name='appsettings',
            name='theme',
            field=models.CharField(
                choices=[('light', 'Light'), ('dark', 'Dark')],
                default='light',
                help_text='UI theme preference',
                max_length=10
            ),
        ),
    ]
