# Generated by Django 5.1.6 on 2025-11-07 21:47

from django.db import migrations


def update_action_values(apps, schema_editor):
    """Convert old action values to new ones"""

    # Get all junction table models
    ProjectAlias = apps.get_model('core', 'ProjectAlias')
    ProjectZone = apps.get_model('core', 'ProjectZone')
    ProjectFabric = apps.get_model('core', 'ProjectFabric')
    ProjectSwitch = apps.get_model('core', 'ProjectSwitch')
    ProjectStorage = apps.get_model('core', 'ProjectStorage')
    ProjectVolume = apps.get_model('core', 'ProjectVolume')
    ProjectHost = apps.get_model('core', 'ProjectHost')
    ProjectPort = apps.get_model('core', 'ProjectPort')

    # Update each table
    for Model in [ProjectAlias, ProjectZone, ProjectFabric, ProjectSwitch,
                  ProjectStorage, ProjectVolume, ProjectHost, ProjectPort]:
        # Convert 'create' to 'new'
        Model.objects.filter(action='create').update(action='new')

        # Convert 'modify' to 'modified'
        Model.objects.filter(action='modify').update(action='modified')

        # Convert 'reference' to 'unmodified'
        Model.objects.filter(action='reference').update(action='unmodified')


def reverse_update_action_values(apps, schema_editor):
    """Reverse the action value conversion"""

    # Get all junction table models
    ProjectAlias = apps.get_model('core', 'ProjectAlias')
    ProjectZone = apps.get_model('core', 'ProjectZone')
    ProjectFabric = apps.get_model('core', 'ProjectFabric')
    ProjectSwitch = apps.get_model('core', 'ProjectSwitch')
    ProjectStorage = apps.get_model('core', 'ProjectStorage')
    ProjectVolume = apps.get_model('core', 'ProjectVolume')
    ProjectHost = apps.get_model('core', 'ProjectHost')
    ProjectPort = apps.get_model('core', 'ProjectPort')

    # Update each table
    for Model in [ProjectAlias, ProjectZone, ProjectFabric, ProjectSwitch,
                  ProjectStorage, ProjectVolume, ProjectHost, ProjectPort]:
        # Convert 'modified' back to 'modify'
        Model.objects.filter(action='modified').update(action='modify')

        # Convert 'unmodified' back to 'reference'
        Model.objects.filter(action='unmodified').update(action='reference')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_projectalias_delete_me_projectfabric_delete_me_and_more'),
    ]

    operations = [
        migrations.RunPython(
            update_action_values,
            reverse_code=reverse_update_action_values
        ),
    ]
