# Generated by Django 5.1.6 on 2025-09-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20250924_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableconfiguration',
            name='page_size',
            field=models.CharField(choices=[('25', '25'), ('50', '50'), ('100', '100'), ('250', '250'), ('All', 'All')], default='25', help_text='Number of rows per page', max_length=10),
        ),
    ]
