# Generated by Django 5.1.6 on 2025-11-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_update_action_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectalias',
            name='do_not_include_in_zoning',
            field=models.BooleanField(default=False, help_text='Manual override to force exclusion from zone generation (highest priority)'),
        ),
        migrations.AlterField(
            model_name='projectalias',
            name='include_in_zoning',
            field=models.BooleanField(default=False, help_text='Manual override to force inclusion in zone generation (overrides deployed status)'),
        ),
    ]
