# Generated by Django 5.1.6 on 2025-10-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_tableconfiguration_page_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableconfiguration',
            name='page_size',
            field=models.IntegerField(default=25, help_text='Number of rows per page'),
        ),
    ]
