# Generated by Django 5.1.6 on 2025-12-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_projectalias_do_not_include_in_zoning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='hide_mode_banners',
            field=models.BooleanField(default=False, help_text='Hide Committed/Draft mode banners in table views'),
        ),
    ]
