# Generated by Django 5.1.6 on 2025-10-04 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_tableconfiguration_page_size'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns this project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', help_text="User's role for this customer", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(help_text='Customer this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='customers.customer')),
                ('user', models.ForeignKey(help_text='User who is a member of this customer', on_delete=django.db.models.deletion.CASCADE, related_name='customer_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Membership',
                'verbose_name_plural': 'Customer Memberships',
                'indexes': [models.Index(fields=['customer', 'user'], name='core_custom_custome_3dc4dd_idx'), models.Index(fields=['user', 'role'], name='core_custom_user_id_f12e16_idx')],
                'unique_together': {('customer', 'user')},
            },
        ),
    ]
