# Generated by Django 5.1.6 on 2025-12-18 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_pool_model'),
        ('storage', '0011_add_pool_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpool',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='storage.pool'),
        ),
        migrations.AddField(
            model_name='projectpool',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_pools', to='core.project'),
        ),
        migrations.AddIndex(
            model_name='projectpool',
            index=models.Index(fields=['project', 'action'], name='core_projec_project_cdf56a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpool',
            index=models.Index(fields=['pool', 'action'], name='core_projec_pool_id_b989ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectpool',
            unique_together={('project', 'pool')},
        ),
    ]
