# Generated by Django 5.1.6 on 2025-10-05 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_project_created_at_project_owner_project_updated_at_and_more'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('group', 'Group')], default='private', help_text='Project visibility: private (owner only), public (all customer users), or group (group members)', max_length=10),
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the project group', max_length=200)),
                ('description', models.TextField(blank=True, help_text="Optional description of the group's purpose", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this group', on_delete=django.db.models.deletion.CASCADE, related_name='created_project_groups', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer this group belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='project_groups', to='customers.customer')),
                ('members', models.ManyToManyField(blank=True, help_text='Users who are members of this group', related_name='project_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Group',
                'verbose_name_plural': 'Project Groups',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ForeignKey(blank=True, help_text="Group that has access to this project (only used when visibility='group')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.projectgroup'),
        ),
        migrations.AddIndex(
            model_name='projectgroup',
            index=models.Index(fields=['customer', 'name'], name='core_projec_custome_b2bac8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectgroup',
            unique_together={('customer', 'name')},
        ),
    ]
