# Generated by Django 5.1.6 on 2025-12-31 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_projectibmilpar_projectvolumemapping_and_more'),
        ('storage', '0014_hostcluster_ibmilpar_volumemapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthostcluster',
            name='host_cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='storage.hostcluster'),
        ),
        migrations.AddField(
            model_name='projecthostcluster',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_host_clusters', to='core.project'),
        ),
        migrations.AddField(
            model_name='projectibmilpar',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_project_ibmi_lpars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectibmilpar',
            name='ibmi_lpar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='storage.ibmilpar'),
        ),
        migrations.AddField(
            model_name='projectibmilpar',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_ibmi_lpars', to='core.project'),
        ),
        migrations.AddField(
            model_name='projectvolumemapping',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_project_volume_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectvolumemapping',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_volume_mappings', to='core.project'),
        ),
        migrations.AddField(
            model_name='projectvolumemapping',
            name='volume_mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='storage.volumemapping'),
        ),
        migrations.AddIndex(
            model_name='projecthostcluster',
            index=models.Index(fields=['project', 'action'], name='core_projec_project_992f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='projecthostcluster',
            index=models.Index(fields=['host_cluster', 'action'], name='core_projec_host_cl_0db194_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projecthostcluster',
            unique_together={('project', 'host_cluster')},
        ),
        migrations.AddIndex(
            model_name='projectibmilpar',
            index=models.Index(fields=['project', 'action'], name='core_projec_project_98b257_idx'),
        ),
        migrations.AddIndex(
            model_name='projectibmilpar',
            index=models.Index(fields=['ibmi_lpar', 'action'], name='core_projec_ibmi_lp_6ccb77_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectibmilpar',
            unique_together={('project', 'ibmi_lpar')},
        ),
        migrations.AddIndex(
            model_name='projectvolumemapping',
            index=models.Index(fields=['project', 'action'], name='core_projec_project_96741b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectvolumemapping',
            index=models.Index(fields=['volume_mapping', 'action'], name='core_projec_volume__20028c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectvolumemapping',
            unique_together={('project', 'volume_mapping')},
        ),
    ]
