# Generated by Django 5.1.6 on 2026-01-04 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_projecthostcluster_host_cluster_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPPRCPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('new', 'Created in this project'), ('modified', 'Existed but modified in this project'), ('unmodified', 'Existed and has not been modified in this project')], default='new', max_length=10)),
                ('delete_me', models.BooleanField(default=False, help_text='Mark this item for deletion (overrides action for display)')),
                ('field_overrides', models.JSONField(blank=True, default=dict, help_text='Project-specific field values')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Project-specific notes', null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_project_pprc_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project PPRC Path',
                'verbose_name_plural': 'Project PPRC Paths',
                'ordering': ['project', 'pprc_path'],
            },
        ),
    ]
