# Generated by Django 5.1.6 on 2026-01-04 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_pprc_path_models'),
        ('storage', '0018_add_pprc_path_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpprcpath',
            name='pprc_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='storage.pprcpath'),
        ),
        migrations.AddField(
            model_name='projectpprcpath',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_pprc_paths', to='core.project'),
        ),
        migrations.AddIndex(
            model_name='projectpprcpath',
            index=models.Index(fields=['project', 'action'], name='core_projec_project_52c6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpprcpath',
            index=models.Index(fields=['pprc_path', 'action'], name='core_projec_pprc_pa_5309fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectpprcpath',
            unique_together={('project', 'pprc_path')},
        ),
    ]
