# Generated by Django 5.1.6 on 2026-01-04 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_pprc_replication_groups'),
        ('storage', '0019_add_pprc_replication_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpprcreplicationgroup',
            name='pprc_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='storage.pprcreplicationgroup'),
        ),
        migrations.AddField(
            model_name='projectpprcreplicationgroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_pprc_groups', to='core.project'),
        ),
        migrations.AddIndex(
            model_name='projectpprcreplicationgroup',
            index=models.Index(fields=['project', 'action'], name='core_projec_project_f8c776_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpprcreplicationgroup',
            index=models.Index(fields=['pprc_group', 'action'], name='core_projec_pprc_gr_114fa3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectpprcreplicationgroup',
            unique_together={('project', 'pprc_group')},
        ),
    ]
